apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: egress-ip-updater
rules:
  - apiGroups:
      - security.istio.io
    resources:
      - authorizationpolicies
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - ''
    resources:
      - endpoints
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: egress-ip-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: egress-ip-updater
subjects:
  - kind: ServiceAccount
    name: updater
